import QueryProvider from "@/components/providers/query-provider";
import "../globals.css";
import Navbar from "@/components/client/Navbar";
import Providers from "@/components/providers/query-provider";
import localFont from "next/font/local"
import { Playfair_Display } from "next/font/google";
import Footer from "@/components/client/Footer";

export const metadata = {
  title: "Pink Amethyst",
  description: "Generated by Next.js",
};

const PlayfairDisplay = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playfair-display",
});


const Wilkyasta = localFont({
  src: [
    {
      path: '../fonts/wilkysta.ttf',
    }
  ],
  variable: '--font-wilkyasta'
})

export default function ClientLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Wilkyasta.variable} ${PlayfairDisplay.variable} font-sans`}>
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
